services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PROMETHEUS_MULTIPROC_DIR: /tmp/prometheus_multiproc
    volumes:
      - ./ml/saved_model:/app/ml/saved_model

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api